### PR TITLE
added reg_other(), unreg_other() + test cases

### PR DESCRIPTION
**Pull request by uwiger**
Since people keep asking for it ... (e.g. #102)

### CODE REVIEW

**Comment by solvip** [comment]
Fantastic! :+1: 

Why is `p` not supported as a type?  Just curious.

**Comment by uwiger** [comment]
Normal properties are registered in the calling process, i.e. without talking to the gproc server. In order to allow "thread-safe" registration from different processes, this would have to change, which would significantly alter the runtime characteristics of property registration.

**Comment by netDalek** [comment]
great opportunity to connect gproc_pool worker outside of worker

**Comment by uwiger** [comment]
Merged. Sorry about the delay.

**Comment by brentonannan** [comment]
This has been merged a couple months now - any chance it can be considered ready for a release?

**Comment by uwiger** [comment]
@brentonannan, I tagged master as 0.6 a few days ago.

**Comment by brentonannan** [comment]
@uwiger, ah, thanks. Would you mind doing a release to hex.pm when you get a chance?

I'm growing quite fond of gproc, thanks very much for all the work on it.

**Pull request merged**
