### PR TITLE
ensure_reg() and ensure_reg_other()

### PR DESCRIPTION
**Pull request by uwiger**
@spec ensure_reg(Key::key(), Value::value(), Attrs::attrs()) ->
          new | updated

@doc Registers a new name or property unless such and entry (by key) has
already been registered by the current process. If `Key` already exists,
the entry will be updated with the given `Value` and `Attrs`.

This function allows the caller to efficiently register an entry without
first checking whether it has already been registered. An exception is
raised if the name or property is already registered by someone else.
@end

### CODE REVIEW

**Comment by uwiger** [comment]
As far as I can tell, the failing Travis-CI tests are not due to the changes - they have been failing for some time, but all the while, same tests run perfectly on my own machine.

**Comment by jlouis** [comment]
Quick Skim: Looks useful as a test-and-set operation, which we should have more of in Erlang libraries in general.

**Comment by tolbrino** [comment]
LGTM, the failing tests seem unrelated and should be fixed separately.

**Comment by uwiger** [comment]
Thanks! Merged.

**Pull request merged**
