### PR TITLE
test erlang/otp 21, 22

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by getong** [comment]
@uwiger would you take a look at this and make a new tag to hex.pm?

**Comment by paulo-ferraz-oliveira** [comment]
+1

@uwiger: any chance this gets merged and tagged soon?

Thanks

**Comment by paulo-ferraz-oliveira** [comment]
@uwiger: ping 😄

**Comment by manuel-rubio** [comment]
@getong I think you can add now 22.1, 22.2, 22.3 and 23.0.

**Comment by uwiger** [comment]
Closing, since #182 (belatedly) addressed this.

**Pull request closed without merging**
