### PR TITLE
t_sync_cand_dies() must consider all three nodes. Increased timeout

### PR DESCRIPTION
**Pull request by uwiger**
re. issue #145 

Addresses the `case_clause` in `t_sync_cand_dies()`
Increasing overall timeout **may** help, but that's just a guess.

### CODE REVIEW

**Comment by uwiger** [comment]
I added a commit that makes sure `t_fail_node()` doesn't actually stop the master node. While that surely is an interesting case, that's what `t_master_dies()` does.

**Comment by lemenkov** [comment]
Looks good to me.

* https://koji.fedoraproject.org/koji/taskinfo?taskID=22281423

**Comment by uwiger** [comment]
I've added a few more tweaks, since the `t_master_dies()` test case may still time out (though very rarely). Since gen_leader has a 5-second cycle (that _may_ have something to do with it), it seems prudent to wait at least 10 seconds in `gproc_dist:sync()`. The test case should of course allow for at least that much as well.

**Comment by uwiger** [comment]
Still not fully ok, but better, so merged anyway.

**Pull request merged**
