### PR TITLE
function_clause in delete_globals

### PR DESCRIPTION
**Pull request by uwiger**
(Hopefully) addresses Issue #99  (error not reproduced in testing)

### CODE REVIEW

**Comment by comtihon** [comment]
when will it goes to be in master?

**Comment by uwiger** [comment]
My changes were simply based on visual inspection, and I only verified that the code compiles and the original test suite passes. Looking at it again, I spotted a bug, hopefully fixed now.

If you think the latest fix looks more correct than the last one, I'll happily merge right away. ;-)

**Comment by TBK145** [comment]
This fixes a crash for me in the following case:

I have 3 nodes, started with `gproc_dist: list_of_node_names`. They all have the same leader. I run `gproc:reg({n, g, node()}).` on every one of them and then kill the leader node. One of the remaining nodes will crash on the `master` branch, but not on the `uw-delete-globals` branch.

However, in the resulting scenario the new leader node will only 'find' the `{n, g, node()}` he registered, while the node that isn't the new leader will still have all three register entries. `gproc_dist:sync().` did not solve it. Is this expected behavior or a bug?

**Comment by uwiger** [comment]
> However, in the resulting scenario the new leader node will only 'find' the {n, g, node()} he registered, while the node that isn't the new leader will still have all three register entries.

Anytime the nodes end up with different views of what's registered, I'd qualify it as a bug.

Do you have time to try to add a test case to gproc_dist_tests.erl? If not, I can try to find some time later on.

**Comment by TBK145** [comment]
I don't really know how to capture the 2 scenarios I described in tests, so I'll be trying, but I'd rather that you take a shot at it too.

**Pull request closed without merging**
